services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - "./backend/src:/app"
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: restart
          path: backend/src/
  gradio-ui:
    build: ./gradio-ui
    ports:
      - "7860:7860"
    depends_on:
      - backend
    environment:
    - FASTAPI_URL=http://backend:8000/api/chats/
  db_service:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=db-password
      - POSTGRES_DB=mydb
    volumes:
      - dc_managed_db_volume:/var/lib/postgressql/data

volumes:
  dc_managed_db_volume: